@BuberDinner.Api_HostAddress = http://localhost:5205

POST  {{BuberDinner.Api_HostAddress}}/auth/login
Content-Type: application/json

{
    "email":"hgoanglongn@gmail.com",
    "password":"123"
}

###

POST  {{BuberDinner.Api_HostAddress}}/auth/register
Content-Type: application/json

{
    "firstName":"Ami",
    "lastName":"Kaiz",
    "email":"hgoanglongn@gmail.com",
    "password":"123"
}